apiVersion: v1
kind: Service
metadata:
  name: courses-nodeport
  labels:
    app: courses-registration
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30092
  selector:
    app: courses
