apiVersion: v1
kind: ConfigMap
metadata:
  name: courses-config
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://localhost:3306/training-center-courses
    server.port=8070
    ----
    spring.profiles=kubernetes
    spring.datasource.url=jdbc:mysql://registrar-mysql:3306/training-center-courses
    server.port=9000
