apiVersion: v1
kind: ConfigMap
metadata:
  name: students-config
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://localhost:3306/training-center-student
    spring.kafka.bootstrap-servers=localhost:9092
    server.port=8070
    ----
    spring.profile=kubernetes
    spring.datasource.url=jdbc:mysql://registrar-mysql:3306/training-center-student
    server.port=8000